# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'humanai.ui'
#
# Created by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GameWindow(object):
    def setupUi(self, GameWindow):
        GameWindow.setObjectName(_fromUtf8("GameWindow"))
        GameWindow.resize(923, 605)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GameWindow.sizePolicy().hasHeightForWidth())
        GameWindow.setSizePolicy(sizePolicy)
        GameWindow.setWindowOpacity(1.0)
        self.verticalLayoutWidget = QtGui.QWidget(GameWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 10, 521, 481))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridWidgetLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.gridWidgetLayout.setMargin(0)
        self.gridWidgetLayout.setObjectName(_fromUtf8("gridWidgetLayout"))
        self.startButton = QtGui.QPushButton(GameWindow)
        self.startButton.setGeometry(QtCore.QRect(250, 540, 50, 50))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.saveRecordButton = QtGui.QPushButton(GameWindow)
        self.saveRecordButton.setGeometry(QtCore.QRect(430, 540, 80, 50))
        self.saveRecordButton.setObjectName(_fromUtf8("saveRecordButton"))
        self.label = QtGui.QLabel(GameWindow)
        self.label.setGeometry(QtCore.QRect(60, 10, 81, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(GameWindow)
        self.label_2.setGeometry(QtCore.QRect(770, 10, 81, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.endButton = QtGui.QPushButton(GameWindow)
        self.endButton.setGeometry(QtCore.QRect(340, 540, 50, 50))
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.agentEdit1 = QtGui.QLineEdit(GameWindow)
        self.agentEdit1.setGeometry(QtCore.QRect(40, 40, 113, 20))
        self.agentEdit1.setAlignment(QtCore.Qt.AlignCenter)
        self.agentEdit1.setObjectName(_fromUtf8("agentEdit1"))
        self.agentEdit2 = QtGui.QLineEdit(GameWindow)
        self.agentEdit2.setGeometry(QtCore.QRect(760, 40, 113, 20))
        self.agentEdit2.setAlignment(QtCore.Qt.AlignCenter)
        self.agentEdit2.setObjectName(_fromUtf8("agentEdit2"))
        self.leftSquareLabel1 = QtGui.QLabel(GameWindow)
        self.leftSquareLabel1.setGeometry(QtCore.QRect(50, 510, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 114, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.leftSquareLabel1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Courier"))
        font.setPointSize(12)
        self.leftSquareLabel1.setFont(font)
        self.leftSquareLabel1.setText(_fromUtf8(""))
        self.leftSquareLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.leftSquareLabel1.setObjectName(_fromUtf8("leftSquareLabel1"))
        self.leftSquareLabel2 = QtGui.QLabel(GameWindow)
        self.leftSquareLabel2.setGeometry(QtCore.QRect(790, 510, 91, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 114, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.leftSquareLabel2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Courier"))
        font.setPointSize(12)
        self.leftSquareLabel2.setFont(font)
        self.leftSquareLabel2.setText(_fromUtf8(""))
        self.leftSquareLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.leftSquareLabel2.setObjectName(_fromUtf8("leftSquareLabel2"))
        self.resultLabel = QtGui.QLabel(GameWindow)
        self.resultLabel.setGeometry(QtCore.QRect(370, 500, 151, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(116, 114, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.resultLabel.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Courier"))
        font.setPointSize(10)
        self.resultLabel.setFont(font)
        self.resultLabel.setText(_fromUtf8(""))
        self.resultLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.resultLabel.setObjectName(_fromUtf8("resultLabel"))
        self.playerCheck1 = QtGui.QCheckBox(GameWindow)
        self.playerCheck1.setGeometry(QtCore.QRect(50, 70, 92, 23))
        self.playerCheck1.setObjectName(_fromUtf8("playerCheck1"))
        self.playerCheck2 = QtGui.QCheckBox(GameWindow)
        self.playerCheck2.setGeometry(QtCore.QRect(770, 70, 92, 23))
        self.playerCheck2.setObjectName(_fromUtf8("playerCheck2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(GameWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(19, 109, 161, 381))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.pileListLayout0 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.pileListLayout0.setMargin(0)
        self.pileListLayout0.setObjectName(_fromUtf8("pileListLayout0"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(GameWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(750, 120, 160, 371))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.pileListLayout1 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.pileListLayout1.setMargin(0)
        self.pileListLayout1.setObjectName(_fromUtf8("pileListLayout1"))
        self.debugCheck = QtGui.QCheckBox(GameWindow)
        self.debugCheck.setGeometry(QtCore.QRect(560, 550, 81, 23))
        self.debugCheck.setObjectName(_fromUtf8("debugCheck"))

        self.retranslateUi(GameWindow)
        QtCore.QMetaObject.connectSlotsByName(GameWindow)

    def retranslateUi(self, GameWindow):
        GameWindow.setWindowTitle(_translate("GameWindow", "方格斗士", None))
        self.startButton.setText(_translate("GameWindow", "开始", None))
        self.saveRecordButton.setText(_translate("GameWindow", "保存至文件", None))
        self.label.setText(_translate("GameWindow", "agent1", None))
        self.label_2.setText(_translate("GameWindow", "agent2", None))
        self.endButton.setText(_translate("GameWindow", "终止", None))
        self.playerCheck1.setText(_translate("GameWindow", "Human", None))
        self.playerCheck2.setText(_translate("GameWindow", "Human", None))
        self.debugCheck.setText(_translate("GameWindow", "调试信息", None))

